// Code generated by "stringer -type=BinaryOperator"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Add-0]
	_ = x[Subtract-1]
	_ = x[Multiply-2]
	_ = x[Divide-3]
	_ = x[Equal-4]
	_ = x[NotEqual-5]
	_ = x[LessThan-6]
	_ = x[LessThanEqual-7]
	_ = x[GreaterThan-8]
	_ = x[GreaterThanEqual-9]
}

const _BinaryOperator_name = "AddSubtractMultiplyDivideEqualNotEqualLessThanLessThanEqualGreaterThanGreaterThanEqual"

var _BinaryOperator_index = [...]uint8{0, 3, 11, 19, 25, 30, 38, 46, 59, 70, 86}

func (i BinaryOperator) String() string {
	if i < 0 || i >= BinaryOperator(len(_BinaryOperator_index)-1) {
		return "BinaryOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOperator_name[_BinaryOperator_index[i]:_BinaryOperator_index[i+1]]
}
