// Code generated by "stringer -type=BinaryOperator"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Add-0]
	_ = x[Subtract-1]
	_ = x[Multiply-2]
	_ = x[Divide-3]
}

const _BinaryOperator_name = "AddSubtractMultiplyDivide"

var _BinaryOperator_index = [...]uint8{0, 3, 11, 19, 25}

func (i BinaryOperator) String() string {
	if i < 0 || i >= BinaryOperator(len(_BinaryOperator_index)-1) {
		return "BinaryOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinaryOperator_name[_BinaryOperator_index[i]:_BinaryOperator_index[i+1]]
}
